### ISSUE TITLE
String+SHA1.swift does not compile in Xcode 8.3b2, Swift 3.1

### ISSUE THREAD

**Issue by alanzeino** [httpswift/swifter#224]
```
/swifter/Sources/String+SHA1.swift:92:74: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
                let temp = (rotateLeft(a, 5) &+ f &+ e &+ k &+ words[i]) & 0xFFFFFFFF
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```

**Comment by glock45** [comment]
hello,

tried but I can't reproduce it on my side. Let me know, if changing the expresssion to the one below helps:

`let temp = (((rotateLeft(a, 5) &+ f) &+ (e &+ k)) &+ words[i]) & 0xFFFFFFFF`

**Comment by alanzeino** [comment]
Splitting the first part up worked for me:

```
var temp = (rotateLeft(a, 5) &+ f &+ e &+ k &+ words[i])
temp = temp & 0xFFFFFFFF
```

Odd that you don't see it on your side.

**Comment by rudro** [comment]
Alan, this is most likely because they are not using the "-solver-memory-threshold" command line parameter.

**Comment by glock45** [comment]
@rudro what's the value you use?

**Comment by alanzeino** [comment]
Oh right I forgot about that. We do `-solver-memory-threshold 300000`.

**Comment by glock45** [comment]
ok, thanks for sharing 👍

**Comment by rudro** [comment]
> @rudro what's the value you use?

I use whatever Alan tells me to use ;) (we work on the same codebase)
