### ISSUE TITLE
cant build with ubuntu 15.10 

### ISSUE THREAD

**Issue by mtt2p** [httpswift/swifter#121]
i tested it with following swift versions 
**a)** => swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu15.10
`matt@matt-ubu:~/swifter$ which swift `
`/home/matt/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu15.10/usr/bin/swift`
`matt@matt-ubu:~/swifter$ swift build` 
`error: MixedSources("/home/matt/swifter/Sources")`
`matt@matt-ubu:~/swifter$ cd Packages/`
`matt@matt-ubu:~/swifter/Packages$ cd NSLinux-1.1.0/`
`matt@matt-ubu:~/swifter/Packages/NSLinux-1.1.0$ swift build `
`Compiling Swift Module 'NSLinux' (2 sources)
/home/matt/swifter/Packages/NSLinux-1.1.0/Sources/Dispatch.swift:47:57: error: 'COpaquePointer' has been renamed to 'OpaquePointer'
    let unmanaged = Unmanaged<pthreadBlock>.fromOpaque( COpaquePointer( arg ) )
                                                        ^~~~~~~~~~~~~~
                                                        OpaquePointer
/home/matt/swifter/Packages/NSLinux-1.1.0/Sources/Dispatch.swift:55:47: error: value of type 'Unmanaged<pthreadBlock>' has no member 'toOpaque'
    let pointer = UnsafeMutablePointer<Void>( holder.toOpaque() )
                                              ^~~~~~ ~~~~~~~~
/home/matt/swifter/Packages/NSLinux-1.1.0/Sources/Dispatch.swift:76:19: error: missing argument label 'queue:' in call
    dispatch_async( queue, {
                  ^
                    queue: 
/home/matt/swifter/Packages/NSLinux-1.1.0/Sources/NSString.swift:101:52: error: 'joinWithSeparator' has been renamed to 'joined'
        return componentsSeparatedByString( str1 ).joinWithSeparator( str2 )
                                                   ^~~~~~~~~~~~~~~~~
                                                   joined
Swift.Sequence:3:17: note: 'joinWithSeparator' has been explicitly marked unavailable here
    public func joinWithSeparator(_ separator: String) -> String
                ^
/home/matt/swifter/Packages/NSLinux-1.1.0/Sources/NSString.swift:119:26: error: 'fromCString' is unavailable: Please use String.init?(validatingUTF8:) instead. Note that it no longer accepts NULL as a valid input. Also consider using String(cString:), that will attempt to repair ill-formed code units.
            out = String.fromCString( bytes )!
                         ^~~~~~~~~~~
Swift.String:4:24: note: 'fromCString' has been explicitly marked unavailable here
    public static func fromCString(_ cs: UnsafePointer<CChar>) -> String?
                       ^
/home/matt/swifter/Packages/NSLinux-1.1.0/Sources/NSString.swift:119:26: error: 'fromCString' is unavailable: Please use String.init?(validatingUTF8:) instead. Note that it no longer accepts NULL as a valid input. Also consider using String(cString:), that will attempt to repair ill-formed code units.
            out = String.fromCString( bytes )!
                         ^~~~~~~~~~~
Swift.String:4:24: note: 'fromCString' has been explicitly marked unavailable here
    public static func fromCString(_ cs: UnsafePointer<CChar>) -> String?
                       ^
/home/matt/swifter/Packages/NSLinux-1.1.0/Sources/NSString.swift:127:26: error: 'fromCString' is unavailable: Please use String.init?(validatingUTF8:) instead. Note that it no longer accepts NULL as a valid input. Also consider using String(cString:), that will attempt to repair ill-formed code units.
            out = String.fromCString( bytes+index )!
                         ^~~~~~~~~~~
Swift.String:4:24: note: 'fromCString' has been explicitly marked unavailable here
    public static func fromCString(_ cs: UnsafePointer<CChar>) -> String?
                       ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/matt/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/matt/swifter/Packages/NSLinux-1.1.0/.build/debug.yaml default`

**b)**  => swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a-ubuntu15.10
`matt@matt-ubu:~/swifter$ which swift`
`/home/matt/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a-ubuntu15.10/usr/bin/swift`
`matt@matt-ubu:~/swifter$ swift build `
`Compiling Swift Module 'NSLinux' (2 sources)`
`Linking Library:  .build/debug/NSLinux.a`
`Compiling Swift Module 'Swifter' (19 sources)`
`/home/matt/swifter/Sources/HttpServerIO.swift:25:23: warning: extraneous '_' in parameter: 'listenPort' has no keyword argument name
    public func start(_ listenPort: in_port_t = 8080) throws {
                      ^~`....[error.txt](https://github.com/httpswift/swifter/files/221579/error.txt)

i find out in  my Test **a)** the NSLinux lib are not compatible !
in Test **b)** the dependent [NSLinux](https://github.com/johnno1962/NSLinux/commit/f75e9c766d69f2d05785abf62ba51ef3c73a7caa) lib runs fine.
Which swift version i need ?

**Comment by glock45** [comment]
hi @mtt2p 

thank you for the report. I manage to solve all the problems for the latest toolchain (04-12-a) so please go for it :)

Linux
```
VirtualBox:~/Desktop$ export PATH=/home/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu15.10/usr/bin:"${PATH}"
VirtualBox:~/Desktop$ which swift
/home/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu15.10/usr/bin/swift
kolakowski@kolakowski-VirtualBox:~/Desktop$ git clone https://github.com/httpswift/swifter.git
Cloning into 'swifter'...
Checking connectivity... done.
VirtualBox:~/Desktop$ cd swifter/
VirtualBox:~/Desktop/swifter$ swift build
Compiling CSQLite sqlite.c
Linking CSQLite
Compiling Swift Module 'Swifter' (19 sources)
VirtualBox:~/Desktop/swifter$
```
Mac:
```
Damian:~ $ git clone https://github.com/httpswift/swifter.git
Cloning into 'swifter'...
Checking connectivity... done.
Damian:~ $ cd swifter/
Damian:swifter $ export SDKROOT=$(xcrun --show-sdk-path --sdk macosx)
Damian:swifter $ swift build
Compiling CSQLite sqlite.c
Linking CSQLite
Compiling Swift Module 'Swifter' (19 sources)
Damian:swifter $ 
```

**Comment by mtt2p** [comment]
thanks it works (swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu15.10)
```bash
matt@matt-ubu:~/http$ ls -lsa
total 16
4 drwxrwxr-x  2 matt matt 4096 Apr 19 14:19 .
4 drwxr-xr-x 27 matt matt 4096 Apr 19 14:19 ..
4 -rw-rw-r--  1 matt matt  504 Apr 19 14:19 main.swift
4 -rw-rw-r--  1 matt matt  138 Apr 19 14:08 Package.swift
```
```bash
matt@matt-ubu:~/http$ cat main.swift 
//
//  main.swift
//  SwifterSampleLinux
//  Copyright (c) 2015 Damian Kołakowski. All rights reserved.
//

import Foundation
import Swifter
import Glibc

let server = demoServer(NSBundle.mainBundle().resourcePath!)

do {
    server["/testAfterBaseRoute"] = { request in
        return .OK(.Html("ok !"))
    }
    try server.start(9080)
    print("Server has started ( port = 9080 ). Try to connect now...")

    while true {
      sleep(10)
    }
} catch {
    print("Server start error: \(error)")
}
```
```bash
matt@matt-ubu:~/http$ cat Package.swift 
import PackageDescription
 
let package = Package(
  name:"matt",
  dependencies:[
    .Package(url:"../swifter", Version(2, 0, 0))
  ]
)
```
```bash
matt@matt-ubu:~/http$ swift build
Cloning /home/matt/swifter
Resolved version: 2.0.0
mkdir -p /home/matt/http/.build/debug/CSQLite.build
Compiling CSQLite sqlite.c
Linking CSQLite
Compiling Swift Module 'Swifter' (19 sources)
Compiling Swift Module 'matt' (1 sources)
Linking .build/debug/matt
```
```bash
matt@matt-ubu:~/http$ .build/debug/matt
/home/matt/http/.build/debug
Server has started ( port = 9080 ). Try to connect now...
```
please tag the swifter version new to deal with swift built , latest version is 1.1.3 or is it possible to build from the master  branche ?
great project
